import {
  QuickFormFactory,
  LinkageBoxModelFactory,
} from '../modules/dynamic-form';
import { tree } from './mock-tree';
import { options } from './mock-options';

export const  modesss: any = [
  {
    items: [
      new QuickFormFactory({
        label: '是否禁用',
        name: 'yes_no1',
        value: null,
        options: null,
        all: true,
      }).booleanRadio(),
      new QuickFormFactory({
        clear: true,
        data: "datePicker",
        disabled: false,
        format: "YYYY-MM-DD HH:mm:ss",
        help: "",
        kind: "date-time",
        label: "结束日期",
        max: 0,
        min: 1,
        name: "creation_date",
        now: false,
        readonly: true,
        order: 0,
        require: false,
        type: "date-picker",
        validator: "",
        value: "",
      }).datePicker(),
      new LinkageBoxModelFactory({
        label: '族谱',
        name: 'zupu-1',
        require: true,
        tree: tree,
        root: 0,
      }).instance(),
      // new QuickFormFactory({
      //   label: '族谱',
      //   name: 'zupu-2',
      //   tree: this.tree,
      //   root: 0,
      // }).linkageBox(),
      // new QuickFormFactory({
      //   display: '',
      //   label: '图片',
      //   multiple: false,
      //   name: 'image-1',
      //   uploadConfig: {
      //     authTokenHeader: 'Token',
      //     authToken: 'f74f3khvQQr1rk2KvXTc3Gi4D6W74qJ1YFr5EllmLyXujJAaylfq',
      //     url: '/api/access/upload/image',
      //   },
      //   value: null,
      // }).image(),
      // {
      //   label: '族谱',
      //   name: 'zupu-3',
      //   type: 'linkage-box',
      //   value: ['111'],
      //   help: 'this is a password',
      //   order: 1,
      //   tree: this.tree,
      //   root: 0,
      // },
      new QuickFormFactory({
        label: '吃的',
        name: 'radio-2',
        options: options,
        searchConfig: {},
        value: '1',
        text: '只读',
        size: 'tiny',
        // readonly: true,
      }).popupRadio(),
      new QuickFormFactory({
        label: '喝的',
        name: 'radio-3',
        options: options,
        searchConfig: {},
        value: '1',
        text: '只读',
        size: 'small',
        // readonly: true,
      }).popupRadio(),
      new QuickFormFactory({
        label: '用的',
        name: 'radio-4',
        options: options,
        searchConfig: {},
        value: '1',
        text: '只读',
        size: 'medium',
        // readonly: true,
      }).popupRadio(),
      new QuickFormFactory({
        label: '模型',
        name: 'model-1',
        value: '',
        text: '只读',
        min: 0,
        max: 0,
        require: true,
        // readonly: true,
      }).textBox(),
      new QuickFormFactory({
        label: '视频-test-lang-and-lang',
        multiple: true,
        max: 2,
        name: 'video-1',
        uploadConfig: {
          authTokenHeader: 'Token',
          authToken: '3031PAtouX6FtY6u9FPvGsxnZyfG2iWSEBncgHYeFtBV9KZvI28a',
          url: '/api/access/upload/video',
        },
      }).video(),
      new QuickFormFactory({
        label: '多选测试',
        name: 'popup-checkbox-2',
        require: true,
        value: ['A', 1],
        text: {A: '看你的选项', 1: '选项1'},
        options: options,
      }).popupCheckbox(),
      new QuickFormFactory({
        label: '多选测试-2',
        name: 'popup-checkbox-3',
        require: false,
        value: ['A', 1],
        text: {A: '看你的选项', 1: '选项1'},
      }).popupCheckbox(),
    ],
    // title: "活命",
    column: [3,9],
    // hide: true
    size: 'tiny'
  }
];