import {
  QuickFormFactory,
  TextBoxModelFactory,
} from '../modules/dynamic-form';

export const TextboxModels: any = [
  new QuickFormFactory({
    label: '文本',
    name: 'text-1',
    readonly: true,
    min: 2,
    value: '13333',
  }).textBox(),
  new TextBoxModelFactory({
    label: '题库',
    max: 5,
    multiple: true,
    name: 'text-2',
    value: '',
    disabled: false,
    view: false,
  }).instance(),
  {
    "clear": false,
    "disabled": false,
    "kind": "text",
    "placeholder": "请输入你好",
    "readonly": false,
    "value": "",
    "label": "名称",
    "name": "text-title",
    "type": "text-box",
    "help": "产品名称",
    "max": 100,
    "min": 0,
    "order": 0,
    "require": true,
    "validator": "",
    "data": "textBox",
    block: 5,
  },
  {
    "disabled": false,
    "help": "为什么undefined",
    "label": "默认值",
    max: 0,
    min: 0,
    "name": "text-default",
    "order": 0,
    payload: {method: ""},
    "require": false,
    "type": "text-box",
    "validator": "",
    "value": "",
    block: 5,
  },
  new QuickFormFactory({
    block: "0_zh-Hans",
    clear: false,
    disabled: false,
    help: "",
    kind: "url",
    label: "外链",
    max: "0",
    min: "0",
    name: "link_i18n_zh-Hans",
    order: 0,
    payload: {method: 'urlTextBox'},
    placeholder: "",
    readonly: false,
    require: false,
    type: "text-box",
    "validator": "",
    value: ""
  }).urlTextBox(),
  new QuickFormFactory({
    label: '时间',
    name: 'text-time-1',
    clear: true,
    value: '12:34',
    disabled: false,
  }).timeTextBox(),
  new QuickFormFactory({
    label: '时间范围',
    name: 'text-time-range-1',
    help: 'deprecated',
  }).rangeTextBox(),
  new QuickFormFactory({
    label: '数字',
    name: 'text-number-1',
  }).numberTextBox(),
  new QuickFormFactory({
    label: '手机',
    name: 'text-mobile-1',
  }).mobileTextBox(),
  new QuickFormFactory({
    label: '单词',
    name: 'text-letter-name-1',
    min: 2,
  }).letterNameTextBox(),
  new QuickFormFactory({
    label: '文件',
    name: 'text-file-1',
    help: '已废弃'
  }).fileTextBox(),
  new QuickFormFactory({
    label: '英文单词',
    name: 'text-eng-word-1',
  }).englishWordTextBox(),
  new QuickFormFactory({
    label: '邮箱',
    name: 'text-email-1',
    require: false,
  }).emailTextBox(),
  new QuickFormFactory({
    label: '本地时间',
    name: 'text-local-time-1',
    clear: true,
    value: '2022-11-12 11:12'
  }).dateTimeLocalTextBox(),
  new QuickFormFactory({
    label: '中文',
    name: 'text-zh-word-1',
  }).chineseWordTextBox(),
  new QuickFormFactory({
    label: '日期',
    name: 'date-text-1',
    clear: true,
    value: '2022-11-12'
  }).dateTextBox(),
];
