export const  options = [
  { text: '选项A', value: 'A', title : '选项Aigin', items: 99 },
  { text: '选项B', value: 'B', title : '选项B' },
  { text: '选项C', value: 'C', title : '选项ALIGN' },
  { text: '选项D', value: 'D', title : '选项D，我很长哦，你能拿我怎么样呢？我是很长，我就是要换行，今天和诺或，不如出去偶走走快', items: 1000 },
  { text: '选项E', value: 'E', title : '选项E' },
  { text: '选项F', value: 'F', title : '选项F，很长不是你说很长就很长，不是你想要很长，就能很长，很长会换行' },
  { text: '选项G', value: 'Option', title : '选项G', items: 119 },
  { text: '选项H', value: 'H', title : '选项align' },
  { text: '选项I', value: 'I', title : '选项I' },
  { text: '选项J', value: 'J', title : '选项J', items: 69 },
  { text: '选项King', value: 'option', title : '选项K' },
  { text: '选项L', value: 'L', title : '选项L' },
  { text: '选项king', value: 'M', title : '选项M', items: '99+' },
  { text: '选项N', value: 'N', title : '选项N' },
  { text: '选项ki', value: 'getOptions', title : '选项R' },
  { text: '选项1', value: 1, title : '选项1', items: '99+' },
  { text: '选项2', value: 2, title : '选项2' },
  { text: '选项3', value: 3, title : '选项3' },
];